# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theNeighborhood', '0003_auto_20190404_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='theNeighborhood.Neighborhood'),
        ),
    ]
