# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theNeighborhood', '0004_profile_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
